version: '3'

services:
  atom:
    image: dh.press.one/pressone/atom
    env_file:
      - ./config/atom.env
    command: bash -c "/wait-for-it.sh postgres:5432 -- diesel migration run && /app/atom syncserver ${BLOCK_NUM}"
    restart: always
    depends_on:
      - postgres

  atom_web:
    image: dh.press.one/pressone/atom
    env_file:
      - ./config/atom.env
    command: bash -c "/wait-for-it.sh postgres:5432 -- diesel migration run && /app/atom web"
    ports:
      - ${WEB_PORT}:7070
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./postgresql_5:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: pub,pub_wallet,posts,posts_wallet,atom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8e01d6f60c7a846c38d5f99cf3f53383

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - './config/redis.conf:/etc/redis/redis.conf:ro'
    restart: 'always'
